---
- name: Install website using docker image
  hosts: all
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/new_home/.ssh/master
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  
  tasks:
    - name: install python3-docker
      apt:
        name: python3-docker
        state: present
      become: yes
    
    - name: granting permission to Docker
      shell: sudo usermod -aG docker ${USER}
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
    

    - name: Run Docker container
      become: yes
      docker_container:
        name: app
        image: sharagon1/web-project:1.0
        state: started
        detach: yes
        restart_policy: always
        ports:
          - "80:80"