pipeline {
    agent any

    environment {
        // Define environment variables if needed
        ANSIBLE_PLAYBOOK-SERVICES = 'ansible/install-services.yaml'
        ANSIBLE_PLATBOOK-WEB = 'ansible/install-website.yaml'
        PRIVATE_KEY_PATH = '/home/ubuntu/.ssh/master'
        IPS_FILE_PATH = '/home/ubuntu/inventory'

    }

    stages {

        stage('Read Inventory File') {
            steps {
                script {
                    // Read contents of inventory file into IPS_FILE_CONTENT variable
                    IPS_FILE_PATH = sh(script: 'cat /home/ubuntu/inventory', returnStdout: true).trim()
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                    sh "sudo ansible-playbook -i /home/ubuntu/inventory ${ANSIBLE_PLAYBOOK} -u ubuntu"
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                    sh "sudo ansible-playbook -i /home/ubuntu/inventory ${ANSIBLE_PLAYBOOK-WEB} -u ubuntu"
                }
            }
        }
    

    post {
        always {
            // Print 'done' at the end
            sh 'sudo chown -R ubuntu:ubuntu /home/ubuntu/.ssh'
            echo 'Done'

        }
    }
