pipeline {
    agent any

    environment {
        // Define environment variables if needed
        ANSIBLE_PLAYBOOK = 'ansible/install-services.yaml'
        PRIVATE_KEY_PATH = '/home/ubuntu/.ssh/id_rsa'
        IPS_FILE_PATH = 'cat /home/ubuntu/inventory'

    }

    stages {

        stage('Read Inventory File') {
            steps {
                script {
                    // Read contents of inventory file into IPS_FILE_CONTENT variable
                    IPS_FILE_PATH = sh(script: 'cat /home/ubuntu/inventory', returnStdout: true).trim()
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                    
                    

                    // Execute Ansible playbook
                ansiblePlaybook(
                    playbook: "${ANSIBLE_PLAYBOOK}",
                    inventory: "${IPS_FILE_PATH},",
                    )
                }
            }
        }
    }

    post {
        always {
            // Print 'done' at the end
            sh 'sudo chown -R ubuntu:ubuntu /home/ubuntu/.ssh'
            echo 'Done'

        }
    }
