pipeline {
    agent any

    stages {
        stage('Get Public IP') {
            steps {
                script {
                    // You need to somehow get the public IP of the newly created EC2 instance
                    // For example, you can store it as an environment variable or in a file
                    def publicIP = sh(script: "terraform output public_ip", returnStdout: true).trim()
                    env.PUBLIC_IP = publicIP
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                script {
                    // Assuming Ansible is installed and configured
                    sh "ansible-playbook -i '${env.PUBLIC_IP},' playbook.yml"
                }
            }
        }
    }

    post {
        success {
            echo 'Ansible playbook executed successfully!'
        }
        failure {
            echo 'Failed to execute Ansible playbook!'
        }
    }
}
